//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int AccountNumber { get; set; }
        public string BankName { get; set; }
        public string UserName { get; set; }
        public Nullable<int> BalanceAmount { get; set; }
        public string password { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
