//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car()
        {
            this.myBookings = new HashSet<myBooking>();
            this.invoices = new HashSet<invoice>();
            this.Drivers = new HashSet<Driver>();
        }
    
        public string RegistrationId { get; set; }
        public string carName { get; set; }
        public string Model { get; set; }
        public string Image { get; set; }
        public string Color { get; set; }
        public Nullable<bool> Conditioner { get; set; }
        public Nullable<bool> Fuletype { get; set; }
        public Nullable<decimal> RentPerDay { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<bool> CarStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<myBooking> myBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
    }
}
