//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverId { get; set; }
        public string RegistrationId { get; set; }
        public string DriverName { get; set; }
        public Nullable<long> DriverPhoneNum { get; set; }
        public string LicenseDetails { get; set; }
        public Nullable<int> BookingID { get; set; }
    
        public virtual car car { get; set; }
    }
}
