//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expectation
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string ExpectationMessage { get; set; }
        public string StackTrace { get; set; }
        public Nullable<System.DateTime> dateLogedIn { get; set; }
        public string InnerException { get; set; }
        public string GetClassName { get; set; }
        public string URL { get; set; }
    }
}
