//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.myBookings = new HashSet<myBooking>();
            this.Banks = new HashSet<Bank>();
            this.invoices = new HashSet<invoice>();
        }

        [Required(ErrorMessage = "Name is required")]
        public string UserName { get; set; }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Enter your Data Of  Birth")]  
        public Nullable<System.DateTime> DOB { get; set; }
        [Required(ErrorMessage = "Enter your Phone number")]
        public Nullable<long> phoneNumber { get; set; }
        [Required(ErrorMessage = "Enter Password ")]

        public string password { get; set; }
        [Required(ErrorMessage = "Enter Your Email ")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Select The Gender ")]
        public Nullable<bool> Gender { get; set; }
        [Required(ErrorMessage = "Enter Your Address")]

        public string Nationality { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<myBooking> myBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bank> Banks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
        public bool IsValid(out string errorMessage)
        {
            errorMessage = string.Empty;

            // Validate phone number
            if (!phoneNumber.HasValue)
            {
                errorMessage = "Phone number is required.";
                return false;
            }

            if (phoneNumber.ToString().Length != 10 || !phoneNumber.ToString().StartsWith("9"))
            {
                errorMessage = "Phone number should be 10 digits and start with 9.";
                return false;
            }

            // Validate password
            if (string.IsNullOrWhiteSpace(password))
            {
                errorMessage = "Password is required.";
                return false;
            }

            if (password.Length < 6)
            {
                errorMessage = "Password should be at least 6 characters long.";
                return false;
            }

            // Validate DOB
            if (!DOB.HasValue || DOB.Value.AddYears(18) > DateTime.Now)
            {
                errorMessage = "You should be at least 18 years old.";
                return false;
            }

            // Validate email
            if (string.IsNullOrWhiteSpace(Email) || !Email.Contains("@"))
            {
                errorMessage = "Email is invalid.";
                return false;
            }

            return true;
        }
    }
}
